Mox.defmock(BlueJet.EventHandlerMock, for: BlueJet.EventHandler)

Mox.defmock(BlueJet.Catalogue.GoodsServiceMock, for: BlueJet.Catalogue.GoodsService)
Mox.defmock(BlueJet.Catalogue.IdentityServiceMock, for: BlueJet.Catalogue.IdentityService)
Mox.defmock(BlueJet.Catalogue.FileStorageServiceMock, for: BlueJet.Catalogue.FileStorageService)

Mox.defmock(BlueJet.Balance.ServiceMock, for: BlueJet.Balance.Service)
Mox.defmock(BlueJet.Balance.StripeClientMock, for: BlueJet.Balance.StripeClient)
Mox.defmock(BlueJet.Balance.OauthClientMock, for: BlueJet.Balance.OauthClient)
Mox.defmock(BlueJet.Balance.IdentityServiceMock, for: BlueJet.Balance.IdentityService)
Mox.defmock(BlueJet.Balance.CRMServiceMock, for: BlueJet.Balance.CRMService)

Mox.defmock(BlueJet.DataTrading.ServiceMock, for: BlueJet.DataTrading.Service)
Mox.defmock(BlueJet.DataTrading.IdentityServiceMock, for: BlueJet.DataTrading.IdentityService)
Mox.defmock(BlueJet.DataTrading.GoodsServiceMock, for: BlueJet.DataTrading.GoodsService)
Mox.defmock(BlueJet.DataTrading.CRMServiceMock, for: BlueJet.DataTrading.CRMService)
Mox.defmock(BlueJet.DataTrading.CatalogueServiceMock, for: BlueJet.DataTrading.CatalogueService)

Mox.defmock(BlueJet.Fulfillment.ServiceMock, for: BlueJet.Fulfillment.Service)
Mox.defmock(BlueJet.Fulfillment.IdentityServiceMock, for: BlueJet.Fulfillment.IdentityService)
Mox.defmock(BlueJet.Fulfillment.CRMServiceMock, for: BlueJet.Fulfillment.CRMService)
Mox.defmock(BlueJet.Fulfillment.GoodsServiceMock, for: BlueJet.Fulfillment.GoodsService)

Mox.defmock(BlueJet.Storefront.ServiceMock, for: BlueJet.Storefront.Service)
Mox.defmock(BlueJet.Storefront.BalanceServiceMock, for: BlueJet.Storefront.BalanceService)
Mox.defmock(BlueJet.Storefront.FulfillmentServiceMock, for: BlueJet.Storefront.FulfillmentService)
Mox.defmock(BlueJet.Storefront.CatalogueServiceMock, for: BlueJet.Storefront.CatalogueService)
Mox.defmock(BlueJet.Storefront.IdentityServiceMock, for: BlueJet.Storefront.IdentityService)
Mox.defmock(BlueJet.Storefront.GoodsServiceMock, for: BlueJet.Storefront.GoodsService)
Mox.defmock(BlueJet.Storefront.CRMServiceMock, for: BlueJet.Storefront.CRMService)